---
- hosts: localhost
  roles:
    - ./modules 
  vars:
    management_group_name: ChildGroup
  tasks:
    - name: AddSubscriptionToManagementGroup
      azure_rm_managementgroupsubscription:
        group_id: '{{ management_group_name }}'
    