---
- hosts: localhost
  roles:
    - ./modules 
  tasks:
    - name: Create Subscription
      azure_rm_subscriptionfactory:
        enrollment_account_name: myEnrollmentAccount
        offer_type: MS-AZR-0017P
        display_name: Test Ea Azure Sub
        owners:
          - object_id: 973034ff-acb7-409c-b731-e789672c7b31
          - object_id: 67439a9e-8519-4016-a630-f5f805eba567
        additional_parameters:
          custom_data:
            key1: value1
            key2: xxx
