---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateGroup
      azure.rm.apimanagementgroup:                                                                                                                              resource_group: myResourceGroup
        service_name: "{{ service_name }}"
        group_id: myGroup
        display_name: temp group
