---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateNotification 
      azure.rm.apimanagementnotification:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        name: RequestPublisherNotificationMessage
        title: Subscription requests (requiring approval) 
