---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateNotificationRecipientUser
      azure.rm.apimanagementnotificationrecipientuser:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        notification_name: RequestPublisherNotificationMessage
        user_id: "{{ user_name }}"
