---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateProductApi
      azure.rm.apimanagementproductapi:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        api_id: "{{ api_name }}"
        path: newapiPath
