---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: ApiManagementCreateProductGroup                                                                                   
      azure.rm.apimanagementproductgroup:                                                                                       
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
        group_id: myGroup
        display_name: EchoApi
