---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: ApiManagementGetApiContract
      azure.rm.apimanagementapi_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
    - name: ApiManagementGetApiDiagnostic
      azure.rm.apimanagementapidiagnostic_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        diagnostic_id: applicationinsights
    - name: ApiManagementGetApiIssueAttachment
      azure.rm.apimanagementapiissueattachment_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        issue_id: "{{ issue_name }}" 
        attachment_id: myAttachment
    - name: ApiManagementGetApiIssueComment
      azure.rm.apimanagementapiissuecomment_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        issue_id: "{{ issue_name }}" 
        comment_id: myComment
    - name: ApiManagementGetApiOperationPetStore
      azure.rm.apimanagementapioperation_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        operation_id: myOperation
    - name: ApiManagementGetApiRelease
      azure.rm.apimanagementapirelease_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        release_id: myRelease
    - name: ApiManagementGetApiSchema
      azure.rm.apimanagementapischema_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        schema_id: mySchema
    - name: ApiManagementGetApiVersionSet
      azure.rm.apimanagementapiversionset_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        version_set_id: myApiVersionSet
    - name: ApiManagementGetApiOperation
      azure.rm.apimanagementapioperation_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        operation_id: myOperation
    - name: ApiManagementGetAuthorizationServer
      azure.rm.apimanagementauthorizationserver_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        authsid: myAuthorizationServer
    - name: ApiManagementGetBackend
      azure.rm.apimanagementbackend_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        backend_id: myBackend
    - name: ApiManagementGetCache
      azure.rm.apimanagementcache_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        cache_id: westindia
    - name: ApiManagementGetDiagnostic
      azure.rm.apimanagementdiagnostic_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        diagnostic_id: applicationinsights
    - name: ApiManagementGetGroup
      azure.rm.apimanagementgroup_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        group_id: myGroup
    - name: ApiManagementListGroupUsers
      azure.rm.apimanagementgroupuser_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        group_id: myGroup
    - name: ApiManagementGetIdentityProvider
      azure.rm.apimanagementidentityprovider_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        name: microsoft
    - name: ApiManagementGetLogger
      azure.rm.apimanagementlogger_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        logger_id: myLogger
    - name: ApiManagementGetNotification
      azure.rm.apimanagementnotification_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        name: RequestPublisherNotificationMessage
    - name: ApiManagementListNotificationRecipientEmails
      azure.rm.apimanagementnotificationrecipientemail_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        name: RequestPublisherNotificationMessage
    - name: ApiManagementListNotificationRecipientUsers
      azure.rm.apimanagementnotificationrecipientuser_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        name: RequestPublisherNotificationMessage
    - name: ApiManagementGetOpenIdConnectProvider
      azure.rm.apimanagementopenidconnectprovider_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        opid: myOpenidConnectProvider
    - name: ApiManagementGetProduct
      azure.rm.apimanagementproduct_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
    - name: ApiManagementListProductApis
      azure.rm.apimanagementproductapi_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
    - name: ApiManagementListProductGroups
      azure.rm.apimanagementproductgroup_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        product_id: myProduct
    - name: ApiManagementGetProperty
      azure.rm.apimanagementproperty_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        prop_id: myProperty
    - name: ApiManagementServiceGetService
      azure.rm.apimanagementservice_info:
        resource_group: "{{ resource_group }}"
        name: "{{ service_name }}"
    - name: ApiManagementGetSubscription
      azure.rm.apimanagementsubscription_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        sid: testsub
    - name: ApiManagementGetTag
      azure.rm.apimanagementtag_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        tag_id: myTag
    - name: ApiManagementListApiTagDescriptions
      azure.rm.apimanagementapitagdescription_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        api_id: "{{ api_name }}"
        tag_id: myTag
    - name: ApiManagementGetUser
      azure.rm.apimanagementuser_info:
        resource_group: "{{ resource_group }}"
        service_name: "{{ service_name }}"
        user_id: "{{ user_name }}"
