- hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml
  roles:
    - ./modules

  tasks:
  - name: Get Shared Image Gallery information
    azure_rm_computegallery_info:
      resource_group: "{{ resource_group }}"
      name: "{{ shared_gallery_name }}"
    register: output

  - debug:
      var: output
